---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-boilerplate-instance
    image: ghcr.io/shun2992/${MOLECULE_DISTRO:-ubuntu-focal}-molecule:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
